package org.panther.tap5cay3.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.panther.tap5cay3.model.Role;
import org.panther.tap5cay3.model.User;

/**
 * Class _RoleAssignment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RoleAssignment extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EFFECTIVE_DATE_PROPERTY = "effectiveDate";
    public static final String EXPIRATION_DATE_PROPERTY = "expirationDate";
    public static final String ROLE_PROPERTY = "role";
    public static final String USER_PROPERTY = "user";
	public static final String ID_PROPERTY = "id";
	 
    public static final String ID_PK_COLUMN = "id";

    public void setId(Integer	id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setEffectiveDate(Date effectiveDate) {
        writeProperty(EFFECTIVE_DATE_PROPERTY, effectiveDate);
    }
    public Date getEffectiveDate() {
        return (Date)readProperty(EFFECTIVE_DATE_PROPERTY);
    }

    public void setExpirationDate(Date expirationDate) {
        writeProperty(EXPIRATION_DATE_PROPERTY, expirationDate);
    }
    public Date getExpirationDate() {
        return (Date)readProperty(EXPIRATION_DATE_PROPERTY);
    }

    public void setRole(Role role) {
        setToOneTarget(ROLE_PROPERTY, role, true);
    }

    public Role getRole() {
        return (Role)readProperty(ROLE_PROPERTY);
    }


    public void setUser(User user) {
        setToOneTarget(USER_PROPERTY, user, true);
    }

    public User getUser() {
        return (User)readProperty(USER_PROPERTY);
    }


}
