package org.panther.tap5cay3.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.panther.tap5cay3.model.RoleAssignment;

/**
 * Class _Role was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Role extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ENABLED_PROPERTY = "enabled";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String ROLE_ASSIGNMENT_PROPERTY = "roleAssignment";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setEnabled(Boolean enabled) {
        writeProperty(ENABLED_PROPERTY, enabled);
    }
    public Boolean getEnabled() {
        return (Boolean)readProperty(ENABLED_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToRoleAssignment(RoleAssignment obj) {
        addToManyTarget(ROLE_ASSIGNMENT_PROPERTY, obj, true);
    }
    public void removeFromRoleAssignment(RoleAssignment obj) {
        removeToManyTarget(ROLE_ASSIGNMENT_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RoleAssignment> getRoleAssignment() {
        return (List<RoleAssignment>)readProperty(ROLE_ASSIGNMENT_PROPERTY);
    }


}
