package org.panther.tap5cay3.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.panther.tap5cay3.model.RoleAssignment;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String DATE_OF_BIRTH_PROPERTY = "dateOfBirth";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String ID_PROPERTY = "id";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String LOCKED_PROPERTY = "locked";
    public static final String LOGIN_EMAIL_PROPERTY = "loginEmail";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String BOOKING_PROPERTY = "booking";
    public static final String ROLE_ASSIGNMENT_PROPERTY = "roleAssignment";

    public static final String ID_PK_COLUMN = "id";

    public void setDateOfBirth(Date dateOfBirth) {
        writeProperty(DATE_OF_BIRTH_PROPERTY, dateOfBirth);
    }
    public Date getDateOfBirth() {
        return (Date)readProperty(DATE_OF_BIRTH_PROPERTY);
    }

    public void setFirstName(String firstName) {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName() {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setLastName(String lastName) {
        writeProperty(LAST_NAME_PROPERTY, lastName);
    }
    public String getLastName() {
        return (String)readProperty(LAST_NAME_PROPERTY);
    }

    public void setLocked(Boolean locked) {
        writeProperty(LOCKED_PROPERTY, locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty(LOCKED_PROPERTY);
    }

    public void setLoginEmail(String loginEmail) {
        writeProperty(LOGIN_EMAIL_PROPERTY, loginEmail);
    }
    public String getLoginEmail() {
        return (String)readProperty(LOGIN_EMAIL_PROPERTY);
    }

    public void setPassword(String password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public String getPassword() {
        return (String)readProperty(PASSWORD_PROPERTY);
    }


    public void addToRoleAssignment(RoleAssignment obj) {
        addToManyTarget(ROLE_ASSIGNMENT_PROPERTY, obj, true);
    }
    public void removeFromRoleAssignment(RoleAssignment obj) {
        removeToManyTarget(ROLE_ASSIGNMENT_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RoleAssignment> getRoleAssignment() {
        return (List<RoleAssignment>)readProperty(ROLE_ASSIGNMENT_PROPERTY);
    }


}
